services:
  latex-env:
    build:
      context: .
      dockerfile: latex.Dockerfile
    image: latex-docker:u24
    container_name: latex_workspace
    volumes:
      - ~/Latex/klatex:/workspace
    tty: true
    stdin_open: true